apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-pod
spec:
  selector:
    matchLabels:
      project: backend-pod
  template:
    metadata:
      labels:
        project: backend-pod
    spec:
      containers:
        - name: backend-pod
          image: abazuntts/backend-express:1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 20
              periodSeconds: 5
          startupProbe:
              httpGet:
                path: /startup
                port: 8080
              failureThreshold: 6
              periodSeconds: 10
          volumeMounts:
            - name: backend-config-map-file
              mountPath: /app/backend.txt
              subPath: backend.txt
              readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "150Mi"
              cpu: "250m"
          ports:
            - containerPort: 8000
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: backend-config-map
                  key: NODE_ENV
            - name: AUTH_SERVICE_API
              valueFrom:
                configMapKeyRef:
                  name: backend-config-map
                  key: AUTH_SERVICE_API
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: backed-secret
                  key: USERNAME
      volumes:
        - name: backend-config-map-file
          configMap:
            optional: true
            name: backend-config-map-file
